"""Convert raw documents and Q&A dicts to ChatML training format."""

from __future__ import annotations

from typing import Any

from .cleaner import TextCleaner

SYSTEM_PROMPT = (
    "You are FinEdge, an expert personal finance advisor specializing in Indian personal "
    "finance including income tax, mutual funds, insurance, banking, and investments. "
    "Always provide accurate, actionable advice based on current Indian regulations."
)


class ChatMLFormatter:
    """Converts various input formats to ChatML message dicts.

    ChatML format::

        {
            "messages": [
                {"role": "system",    "content": "..."},
                {"role": "user",      "content": "..."},
                {"role": "assistant", "content": "..."}
            ]
        }

    Args:
        system_prompt: Overrides the default FinEdge system prompt.
        cleaner: TextCleaner instance applied to all text fields.
    """

    def __init__(
        self,
        system_prompt: str = SYSTEM_PROMPT,
        cleaner: TextCleaner | None = None,
    ) -> None:
        self._system = system_prompt
        self._cleaner = cleaner or TextCleaner()

    def from_qa_dict(self, qa: dict[str, str]) -> dict[str, Any]:
        """Convert a ``{question, answer}`` dict to ChatML.

        Args:
            qa: Dict with ``question`` and ``answer`` string keys.

        Returns:
            ChatML-formatted dict.

        Raises:
            ValueError: If required keys are missing.
        """
        if "question" not in qa or "answer" not in qa:
            raise ValueError(f"Expected 'question' and 'answer' keys; got {list(qa.keys())}")

        return {
            "messages": [
                {"role": "system", "content": self._system},
                {"role": "user", "content": self._cleaner.clean(qa["question"])},
                {"role": "assistant", "content": self._cleaner.clean(qa["answer"])},
            ]
        }

    def from_raw_document(
        self, content: str, source_metadata: dict | None = None
    ) -> dict[str, Any]:
        """Wrap a raw regulatory document as a single-turn extraction request.

        Useful for converting SEBI/RBI documents into instruction-tuning format
        where the model is asked to summarise or extract key points.

        Args:
            content: Raw document text.
            source_metadata: Metadata dict (source_org, date, circular_no, etc.).

        Returns:
            ChatML-formatted dict.
        """
        meta = source_metadata or {}
        source_tag = ""
        if meta.get("source_org"):
            source_tag = f"[Source: {meta['source_org']}"
            if meta.get("date"):
                source_tag += f", {meta['date']}"
            if meta.get("circular_no") or meta.get("doc_no"):
                source_tag += f", {meta.get('circular_no') or meta.get('doc_no')}"
            source_tag += "]"

        cleaned = self._cleaner.clean(content)
        question = (
            f"Please summarise the key points and regulatory implications of the following "
            f"Indian finance regulation document:\n\n{source_tag}\n\n{cleaned[:3000]}"
        )
        answer = f"This document {source_tag} contains regulatory guidance on:\n\n[Summary to be generated by model during fine-tuning data review]"

        return {
            "messages": [
                {"role": "system", "content": self._system},
                {"role": "user", "content": question},
                {"role": "assistant", "content": answer},
            ]
        }

    def validate_chatml(self, sample: dict) -> bool:
        """Return True if *sample* is a well-formed ChatML dict.

        Args:
            sample: Dict to validate.

        Returns:
            True if valid, False otherwise.
        """
        if "messages" not in sample:
            return False
        messages = sample["messages"]
        if not isinstance(messages, list) or len(messages) < 2:
            return False
        roles = {m.get("role") for m in messages}
        required = {"system", "user", "assistant"}
        return required.issubset(roles)
